SYNONYMS = {
    "womens": ["ladies", "female", "girls", "women's", "womenswear", "ladieswear"],
    "mens": ["male", "men's", "menswear", "gentlemen"],
    "unisex": ["gender-neutral", "all-gender"],
    "kids": ["children", "child", "boy", "girl", "toddler", "youth", "junior", "infant", "baby"],
    
    # Style categories
    "casual": ["informal", "everyday wear", "relaxed"],
    "formal": ["business", "professional", "dressy", "elegant"],
    "party": ["festive", "occasion", "evening wear", "dress-up"],
    "athletic": ["activewear", "sportswear", "gymwear", "workout"],
    "streetwear": ["urban", "hype", "trendy"],
    "vintage": ["retro", "classic", "old-school"],
    "boho": ["bohemian", "hippie", "free-spirited"],
    
    # Clothing items
    "tshirt": ["t-shirts", "t-shirt", "tee", "tees", "t-shirt's", "tee's", "graphic tee"],
    "shirt": ["shirts", "shirt's", "button-up", "button-down", "dress shirt"],
    "jeans": ["denim", "pants", "denims", "skinny jeans", "ripped jeans"],
    "trousers": ["pants", "slacks", "chinos", "dress pants"],
    "shorts": ["bermuda", "cargo shorts", "denim shorts"],
    "jacket": ["coats", "outerwear", "blazer", "windbreaker"],
    "sweater": ["jumper", "pullover", "knitwear", "cardigan"],
    "hoodie": ["hooded sweatshirt", "pullover", "sweatshirt"],
    "sweatshirt": ["hoodie", "crewneck", "fleece"],
    "leggings": ["tights", "yoga pants"],
    "tracksuit": ["jogging suit", "sweatsuit", "warm-up suit"],
    "activewear": ["sportswear", "gym clothes", "workout clothes"],

    # Footwear
    "sneakers": ["trainers", "running shoes", "kicks"],
    "boots": ["ankle boots", "hiking boots", "combat boots"],
    "heels": ["high heels", "stilettos", "pumps"],
    "sandals": ["flip-flops", "slippers", "open-toe shoes"],
    "loafers": ["slip-ons", "formal shoes"],
    "flats": ["ballet flats", "doll shoes"],

    # Accessories
    "hat": ["cap", "beanie", "fedora", "headwear"],
    "scarf": ["shawl", "wrap"],
    "gloves": ["mittens", "handwear"],
    "watch": ["wristwatch", "timepiece"],
    "sunglasses": ["shades", "glasses", "eyewear"],
    "belt": ["waist belt", "strap"],

    # Seasonal clothing
    "summer": ["hot weather", "beachwear", "light clothing"],
    "winter": ["cold weather", "thermal", "insulated"],
    "raincoat": ["waterproof jacket", "trench coat"],

    # Materials
    "denim": ["jean", "jeans fabric"],
    "leather": ["genuine leather", "faux leather", "vegan leather"],
    "cotton": ["organic cotton", "soft fabric"],
    "wool": ["knitwear", "merino wool"],
    "silk": ["satin", "luxury fabric"],
    "linen": ["breathable fabric", "summer fabric"],

    # Patterns & Prints
    "striped": ["stripes", "lined"],
    "checked": ["checkered", "plaid"],
    "floral": ["flower print", "botanical"],
    "solid": ["plain", "single color"],
    "polka dots": ["dots", "spotted"],

    # Color variations
    "black": ["dark", "jet black", "midnight black"],
    "white": ["ivory", "cream", "off-white"],
    "red": ["maroon", "burgundy", "crimson"],
    "blue": ["navy", "sky blue", "royal blue"],
    "green": ["olive", "forest green", "lime"],
    "pink": ["rose", "fuchsia", "magenta"],
    "yellow": ["mustard", "gold"],
    "brown": ["beige", "tan", "chocolate"],
    "gray": ["charcoal", "ash", "slate gray"],

    # Miscellaneous
    "plus-size": ["curvy", "large", "extended sizes"],
    "slim-fit": ["fitted", "tapered"],
    "loose-fit": ["baggy", "oversized"],
    "breathable": ["lightweight", "airy"],
    "waterproof": ["rainproof", "water-resistant"],
    "stretchable": ["elastic", "flexible"],
    
    
    # spelling
    "casual": ["casual wear", "casualwear", "casual-wear"],
    "formal": ["formal wear", "formalwear", "formal-wear"],
    "ethnic": ["ethnic wear", "ethnicwear", "ethnic-wear"],
    "western": ["western wear", "westernwear", "western-wear"],
    "sports": ["sportswear", "sports-wear", "sports clothing", "athletic wear", "sports apparel"],
    "active": ["activewear", "active-wear", "active clothing", "workout wear", "gym wear"],
    "party": ["party wear", "partywear", "party-wear"],
    "winter": ["winter wear", "winterwear", "winter-wear"],
    "summer": ["summer wear", "summerwear", "summer-wear"],
    "outer": ["outerwear", "outer-wear", "jackets", "coats", "winter clothing"],
    "lounge": ["loungewear", "lounge-wear", "home wear", "home clothing"],
    "night": ["nightwear", "night-wear", "sleepwear", "pyjamas", "pajamas"],
    "inner": ["innerwear", "inner-wear", "lingerie", "undergarments", "intimates"],
    "denim": ["denim & jeans", "jeans", "denimwear", "denim-wear"],
    "tops": ["tops & t-shirts", "tshirts", "t-shirts", "tees", "t shirts"],
    "t-shirts": ["tops & t-shirts", "tshirts", "tees", "t shirts", "t-shirts"],
    "shirts": ["shirts", "formal shirts", "casual shirts"],
    "dresses": ["dresses", "gowns", "frocks"],
    "suits": ["suits & blazers", "blazers", "formal suits", "tuxedos", "coats"],
    "kurtas": ["kurta & kurtis", "kurtis", "kurtas", "ethnic kurtas", "Indian kurtis"],
    "lehengas": ["lehengas", "bridal lehengas", "festive lehengas"],
    "sarees": ["sarees", "saris", "traditional sarees", "ethnic sarees"],
    "accessories": ["accessories", "fashion accessories", "add-ons"],
    "footwear": ["footwear", "shoes", "sandals", "sneakers", "boots"],
    "handbags": ["handbags & wallets", "wallets", "purses", "bags"],
    "jewelry": ["jewelry", "jewellery", "ornaments", "fashion jewelry"],
    "watches": ["watches", "wristwatches", "timepieces"],
    "bags": ["bags & backpacks", "backpacks", "rucksacks", "school bags"],
    "kidswear": ["kidswear", "children's clothing", "kids clothing"],
    "unisex": ["unisex apparel", "gender-neutral clothing", "unisex wear"],
    "combo": ["combo sets", "clothing sets", "outfits", "bundles"],
    "festival": ["festival wear", "festive clothing", "special occasion wear"],
    "indo-western": ["indo-western wear", "fusion wear", "indo-western outfits"],
    "swimwear": ["swimwear", "swimsuits", "beachwear", "bathing suits"],
    "beachwear": ["beachwear", "resort wear", "tropical clothing"],
    "uniforms": ["uniforms", "workwear", "school uniforms"],
    "office": ["office wear", "workwear", "business clothing"],
    "maternity": ["maternity wear", "pregnancy clothing", "maternity dresses"],
    "plus size": ["plus size clothing", "plus-size apparel", "extended sizes"],
    "bridal": ["bridal wear", "wedding dresses", "bridal lehengas"],
    "groom": ["groom wear", "wedding suits", "sherwanis"],
    "sports accessories": ["sports accessories", "gym gear", "athletic accessories"],
    "travel": ["travel gear", "luggage", "travel bags"],
    "beauty": ["beauty products", "cosmetics", "skincare", "makeup"],
    "active accessories": ["active accessories", "fitness gear", "workout accessories"],
    "luxury": ["luxury wear", "designer wear", "premium clothing"],
    "sustainable": ["sustainable wear", "eco-friendly clothing", "sustainable fashion"]
}

STOP_WORDS = set({'a',  'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 'her',
 'here',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'i',
 'if',
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it's",
 'its',
 'itself',
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she's",
 'should',
 "should've",
 'shouldn',
 "shouldn't",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 'were',
 'weren',
 "weren't",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 "you're",
 "you've",
 'your',
 'yours',
 'yourself',
 'yourselves'})
